# Generated by Django 3.2.12 on 2022-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/sample.jpg', upload_to='images/'),
        ),
    ]
